"""added published 

Revision ID: 43476dd9a94a
Revises: 
Create Date: 2021-03-08 14:36:32.916019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43476dd9a94a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('published', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'posts', ['slug'])
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.VARCHAR(length=120), nullable=True))
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'published')
    # ### end Alembic commands ###
